# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(863, 503)
        Dialog.setStyleSheet("")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(160, 100, 261, 391))
        self.label_2.setStyleSheet("background:none;\n"
"")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Icons/580b57fbd9996e24bc43be13.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(150, 40, 631, 391))
        self.label.setStyleSheet("border-radius:20px;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Icons/david-becker-crs2vlkSe98-unsplash.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(500, 90, 181, 51))
        self.label_3.setStyleSheet("background-color: rgb(221, 221, 221);\n"
"font: 87 14pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 85, 255);\n"
"border-radius:5px;")
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(430, 120, 321, 201))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(30, 40, 261, 51))
        self.lineEdit.setStyleSheet("font: 12pt \"Arial Unicode MS\";\n"
"border-radius:10px;\n"
"background-color: rgb(227, 227, 227);\n"
"border:1px solid lightgrey;")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 110, 261, 51))
        self.lineEdit_2.setStyleSheet("font: 12pt \"Arial Unicode MS\";\n"
"border-radius:10px;\n"
"background-color: rgb(227, 227, 227);\n"
"border:1px solid lightgrey;")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(480, 340, 221, 41))
        self.pushButton.setStyleSheet("QPushButton{background-color: rgb(85, 255, 127);\n"
"color: rgb(0, 85, 127);\n"
"font: 87 12pt \"Arial Black\";\n"
"border-radius:15px;\n"
"border:2px solid white;}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color: rgb(188, 74, 143);\n"
"    color: rgb(255, 255, 255);\n"
"border:2px solid white;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(790, 40, 41, 31))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 85, 255);\n"
"\n"
"\n"
"font: 87 14pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"border-radius5px;}\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 0, 255);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label.raise_()
        self.label_2.raise_()
        self.frame.raise_()
        self.label_3.raise_()
        self.pushButton.raise_()
        self.pushButton_4.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "User Login"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "Username"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "Password"))
        self.pushButton.setText(_translate("Dialog", "LOGIN"))
        self.pushButton_4.setText(_translate("Dialog", "X"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Login()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
