# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newenquiry.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewEnquiry(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(652, 734)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.983, y1:0.363636, x2:1, y2:1, stop:0.136364 rgba(48, 61, 158, 248), stop:0.755682 rgba(148, 61, 243, 255));\n"
"\n"
"border-radius:10;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(160, 60, 281, 41))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 20pt \"Arial Black\";\n"
"\n"
"background:none;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(80, 110, 221, 41))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 130, 80);\n"
"color: rgb(255, 255, 255);\n"
"    \n"
"    font: 87 10pt \"Arial Black\";\n"
"border:2px solid grey;}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 85, 127);\n"
"border:2px solid white;}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 110, 231, 41))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 130, 80);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 10pt \"Arial Black\";\n"
"border:2px solid grey;}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 85, 127);\n"
"border:2px solid white;}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(580, 10, 41, 31))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 85, 255);\n"
"\n"
"\n"
"font: 87 14pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"border-radius5px;}\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 0, 255);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(30, 160, 571, 531))
        self.frame_2.setStyleSheet("background-color: rgb(233, 234, 223);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 161, 31))
        self.label_2.setStyleSheet("font: 75 12pt \"Arial Narrow\";\n"
"font: 87 10pt \"Arial Black\";\n"
"color: rgb(0, 85, 127);")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(200, 30, 261, 31))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QLineEdit:hover{\n"
"border:2px solid blue;\n"
"}")
        self.lineEdit.setCursorPosition(0)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 171, 31))
        self.label_3.setStyleSheet("font: 75 12pt \"Arial Narrow\";\n"
"font: 87 10pt \"Arial Black\";\n"
"color: rgb(0, 85, 127);")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(80, 400, 111, 31))
        self.label_6.setStyleSheet("font: 75 12pt \"Arial Narrow\";\n"
"font: 87 10pt \"Arial Black\";\n"
"color: rgb(0, 85, 127);")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(200, 380, 261, 71))
        self.plainTextEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(310, 470, 151, 41))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"    \n"
"    font: 87 10pt \"Arial Black\";\n"
"border:2px solid grey;}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 85, 127);\n"
"border:2px solid white;}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/Icons/diskette (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(200, 240, 261, 31))
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QLineEdit:hover{\n"
"border:2px solid blue;\n"
"}")
        self.lineEdit_3.setCursorPosition(0)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(80, 240, 111, 31))
        self.label_11.setStyleSheet("font: 75 12pt \"Arial Narrow\";\n"
"font: 87 10pt \"Arial Black\";\n"
"color: rgb(0, 85, 127);")
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(200, 100, 261, 31))
        self.lineEdit_5.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QLineEdit:hover{\n"
"border:2px solid blue;\n"
"}")
        self.lineEdit_5.setCursorPosition(0)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 171, 31))
        self.label_4.setStyleSheet("font: 75 12pt \"Arial Narrow\";\n"
"font: 87 10pt \"Arial Black\";\n"
"color: rgb(0, 85, 127);")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(200, 170, 261, 31))
        self.lineEdit_6.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QLineEdit:hover{\n"
"border:2px solid blue;\n"
"}")
        self.lineEdit_6.setCursorPosition(0)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(20, 310, 171, 31))
        self.label_5.setStyleSheet("font: 75 12pt \"Arial Narrow\";\n"
"font: 87 10pt \"Arial Black\";\n"
"color: rgb(0, 85, 127);")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(200, 310, 261, 31))
        self.lineEdit_7.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QLineEdit:hover{\n"
"border:2px solid blue;\n"
"}")
        self.lineEdit_7.setCursorPosition(0)
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 571, 531))
        self.frame_3.setStyleSheet("background-color: rgb(233, 234, 223);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(10, 30, 111, 31))
        self.label_7.setStyleSheet("font: 75 12pt \"Arial Narrow\";\n"
"font: 87 10pt \"Arial Black\";\n"
"color: rgb(0, 85, 127);")
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 30, 211, 31))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QLineEdit:hover{\n"
"border:2px solid blue;\n"
"}")
        self.lineEdit_2.setCursorPosition(0)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(10, 100, 111, 31))
        self.label_8.setStyleSheet("font: 75 12pt \"Arial Narrow\";\n"
"font: 87 10pt \"Arial Black\";\n"
"color: rgb(0, 85, 127);")
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.comboBox = QtWidgets.QComboBox(self.frame_3)
        self.comboBox.setGeometry(QtCore.QRect(130, 100, 211, 31))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setEditable(True)
        self.comboBox.setFrame(False)
        self.comboBox.setObjectName("comboBox")
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setGeometry(QtCore.QRect(10, 170, 111, 31))
        self.label_9.setStyleSheet("font: 75 12pt \"Arial Narrow\";\n"
"font: 87 10pt \"Arial Black\";\n"
"color: rgb(0, 85, 127);")
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.dateEdit = QtWidgets.QDateEdit(self.frame_3)
        self.dateEdit.setGeometry(QtCore.QRect(130, 170, 91, 31))
        self.dateEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_4.setGeometry(QtCore.QRect(280, 170, 61, 31))
        self.lineEdit_4.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"")
        self.lineEdit_4.setCursorPosition(0)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(230, 170, 41, 31))
        self.label_10.setStyleSheet("font: 75 12pt \"Arial Narrow\";\n"
"font: 87 10pt \"Arial Black\";\n"
"color: rgb(0, 85, 127);")
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setGeometry(QtCore.QRect(10, 420, 111, 31))
        self.label_12.setStyleSheet("font: 75 12pt \"Arial Narrow\";\n"
"font: 87 10pt \"Arial Black\";\n"
"color: rgb(0, 85, 127);")
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.frame_3)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(130, 410, 211, 51))
        self.plainTextEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        self.label_13.setGeometry(QtCore.QRect(390, 30, 131, 131))
        self.label_13.setStyleSheet("font: 75 12pt \"Arial Narrow\";\n"
"\n"
"font: 87 10pt \"Arial Black\";\n"
"color: rgb(0, 85, 127);")
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/images/Icons/img_415067.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_3.setGeometry(QtCore.QRect(400, 170, 111, 31))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 130, 80);\n"
"color: rgb(255, 255, 255);\n"
"    \n"
"    font: 87 10pt \"Arial Black\";\n"
"border:2px solid grey;}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 85, 127);\n"
"border:2px solid white;}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.frame_3)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(360, 350, 181, 111))
        self.plainTextEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setGeometry(QtCore.QRect(400, 330, 111, 21))
        self.label_14.setStyleSheet("font: 75 12pt \"Arial Narrow\";\n"
"font: 87 10pt \"Arial Black\";\n"
"color: rgb(0, 85, 127);")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        self.label_15.setGeometry(QtCore.QRect(400, 260, 101, 31))
        self.label_15.setStyleSheet("font: 75 12pt \"Arial Narrow\";\n"
"font: 87 10pt \"Arial Black\";\n"
"color: rgb(0, 85, 127);")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.frame_3)
        self.dateEdit_2.setGeometry(QtCore.QRect(370, 290, 171, 31))
        self.dateEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_6.setGeometry(QtCore.QRect(380, 470, 161, 41))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"    \n"
"    font: 87 10pt \"Arial Black\";\n"
"border:2px solid grey;}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 85, 127);\n"
"border:2px solid white;}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_8.setGeometry(QtCore.QRect(130, 230, 211, 31))
        self.lineEdit_8.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QLineEdit:hover{\n"
"border:2px solid blue;\n"
"}")
        self.lineEdit_8.setCursorPosition(0)
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_16 = QtWidgets.QLabel(self.frame_3)
        self.label_16.setGeometry(QtCore.QRect(10, 230, 111, 31))
        self.label_16.setStyleSheet("font: 75 12pt \"Arial Narrow\";\n"
"font: 87 10pt \"Arial Black\";\n"
"color: rgb(0, 85, 127);")
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_9.setGeometry(QtCore.QRect(130, 290, 211, 31))
        self.lineEdit_9.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QLineEdit:hover{\n"
"border:2px solid blue;\n"
"}")
        self.lineEdit_9.setCursorPosition(0)
        self.lineEdit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_17 = QtWidgets.QLabel(self.frame_3)
        self.label_17.setGeometry(QtCore.QRect(10, 290, 111, 31))
        self.label_17.setStyleSheet("font: 75 12pt \"Arial Narrow\";\n"
"font: 87 10pt \"Arial Black\";\n"
"color: rgb(0, 85, 127);")
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_10.setGeometry(QtCore.QRect(130, 350, 211, 31))
        self.lineEdit_10.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QLineEdit:hover{\n"
"border:2px solid blue;\n"
"}")
        self.lineEdit_10.setCursorPosition(0)
        self.lineEdit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_18 = QtWidgets.QLabel(self.frame_3)
        self.label_18.setGeometry(QtCore.QRect(0, 350, 121, 31))
        self.label_18.setStyleSheet("font: 75 12pt \"Arial Narrow\";\n"
"font: 87 10pt \"Arial Black\";\n"
"color: rgb(0, 85, 127);")
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame_3)
        self.label_19.setGeometry(QtCore.QRect(400, 210, 101, 16))
        self.label_19.setStyleSheet("font: 75 12pt \"Arial Narrow\";\n"
"font: 87 10pt \"Arial Black\";\n"
"color: rgb(0, 85, 127);")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_2.setGeometry(QtCore.QRect(370, 230, 171, 31))
        self.comboBox_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0;")
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setFrame(False)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_20 = QtWidgets.QLabel(self.frame_3)
        self.label_20.setGeometry(QtCore.QRect(10, 480, 111, 31))
        self.label_20.setStyleSheet("font: 75 12pt \"Arial Narrow\";\n"
"font: 87 10pt \"Arial Black\";\n"
"color: rgb(0, 85, 127);")
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_3.setGeometry(QtCore.QRect(130, 480, 211, 31))
        self.comboBox_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0;")
        self.comboBox_3.setEditable(False)
        self.comboBox_3.setFrame(False)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(20, 10, 81, 31))
        self.label_21.setStyleSheet("font: 75 12pt \"Arial Narrow\";\n"
"font: 87 10pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color:none;")
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame)
        self.label_22.setGeometry(QtCore.QRect(110, 10, 81, 31))
        self.label_22.setStyleSheet("font: 75 12pt \"Arial Narrow\";\n"
"font: 87 10pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color:none;")
        self.label_22.setText("")
        self.label_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "New Enquiry"))
        self.pushButton.setText(_translate("Dialog", "Student Detail"))
        self.pushButton_2.setText(_translate("Dialog", "Parent Detail"))
        self.pushButton_4.setText(_translate("Dialog", "X"))
        self.label_2.setText(_translate("Dialog", "Father\'s Name"))
        self.label_3.setText(_translate("Dialog", "Mobile Number"))
        self.label_6.setText(_translate("Dialog", "Address"))
        self.pushButton_5.setText(_translate("Dialog", "SAVE"))
        self.label_11.setText(_translate("Dialog", "Mother\'s Name"))
        self.label_4.setText(_translate("Dialog", "Father\'s Occupation"))
        self.label_5.setText(_translate("Dialog", "Mobile Number"))
        self.label_7.setText(_translate("Dialog", "Student Name"))
        self.label_8.setText(_translate("Dialog", "Class / Course"))
        self.label_9.setText(_translate("Dialog", "Date Of Birth"))
        self.label_10.setText(_translate("Dialog", "Age"))
        self.label_12.setText(_translate("Dialog", "Address"))
        self.pushButton_3.setText(_translate("Dialog", "Photo"))
        self.label_14.setText(_translate("Dialog", "Remark"))
        self.label_15.setText(_translate("Dialog", "Reminder"))
        self.pushButton_6.setText(_translate("Dialog", "Parent Detail"))
        self.label_16.setText(_translate("Dialog", "Mobile Number"))
        self.label_17.setText(_translate("Dialog", "Email"))
        self.label_18.setText(_translate("Dialog", "School / College"))
        self.label_19.setText(_translate("Dialog", "Gender"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "Male"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "Female"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "Other"))
        self.label_20.setText(_translate("Dialog", "Enrolled"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "No"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "Yes"))
        self.comboBox_3.setItemText(2, _translate("Dialog", "Tentative"))
        self.label_21.setText(_translate("Dialog", "Enquiry ID:"))
import resources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_NewEnquiry()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
