# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'studentlist.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StudentList(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1210, 707)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet("QFrame{\n"
"\n"
"background-color: qlineargradient(spread:pad, x1:0.983, y1:0.363636, x2:1, y2:1, stop:0.136364 rgba(48, 61, 158, 248), stop:0.755682 rgba(148, 61, 243, 255));\n"
"\n"
"border-radius:10;\n"
"border:2px solid white;\n"
";}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 15, 221, 31))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 16pt \"Arial Black\";\n"
"background-color:none;\n"
"border:none;")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(980, 50, 191, 41))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 130, 80);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 10pt \"Arial Black\";\n"
"border-radius:10;\n"
"border:2px solid grey;}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 85, 127);\n"
"border:2px solid white;}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/Icons/send.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(24, 24))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(20, 50, 301, 41))
        self.lineEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 127);\n"
"border:1px solid white;")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(20, 100, 1151, 561))
        self.tableWidget.setStyleSheet("background-color: rgb(212, 212, 212);\n"
"border-radius:0px;\n"
"border:none;")
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setRowCount(20)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(112)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(1130, 10, 41, 31))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 85, 255);\n"
"\n"
"\n"
"font: 87 14pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"border-radius5px;}\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 0, 255);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "ENQUIRY LIST"))
        self.pushButton.setText(_translate("Dialog", "Export"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "SEARCH HERE"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "ENQUIRY ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "NAME"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "FATHER\'S NAME"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "DOB"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "EMAIL"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "MOB. NO."))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "REMARK"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "REMINDER"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "EDIT"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Dialog", "MESSAGE"))
        self.pushButton_4.setText(_translate("Dialog", "X"))
import resources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_StudentList()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
